version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/posgresql/data
    user: postgres
    environment:
      - POSTGRES_DB=ayomi
      - POSTGRES_USER=pilouventre
      - POSTGRES_PASS=testpswd
      - POSTGRES_PASSWORD=password
  web:
    build: .
    volumes: 
      - .:/mysite
    ports:
      - 8001:8001
    image: app:mysite
    container_name : container
    command: python manage.py runserver 0.0.0.0:8001
    depends_on:
      - db
volumes:
  pgdata: